Update agot_culture_gfx_l_spanish.yml
Sauronato/AGOTSpanish pull request #35
Opened 2023-04-30 14:30 UTC by MikiDrac

Propongo una revisión (parcial) de lo que he modificado.

## Cambios realizados

## Problema relacionado (opcional)

## Comprobación de pruebas(opcional)

## Comentarios adicionales (opcional)

2023-04-30 17:14 UTC, Js-glez requested changes
Todo perfecto menos el detalle señalado.

2023-04-30 17:14 UTC, Js-glez commented on C/localization/spanish/culture/agot_culture_gfx_l_spanish.yml
> + crownlander_unit_gfx:0 "Corononense" #NT!
Hemos estado hablando y _coronense_ no está considerado como una palabra exacta, se prefiere la traducción anterior.

2023-04-30 17:40 UTC, MikiDrac commented on C/localization/spanish/culture/agot_culture_gfx_l_spanish.yml
> + crownlander_unit_gfx:0 "Corononense" #NT!
De acuerdo! Entonces la primera letra tendría que ir en minúscula: "de las Tierras de la Corona".

2023-05-01 09:11 UTC, Js-glez commented on C/localization/spanish/culture/agot_culture_gfx_l_spanish.yml
> + crownlander_unit_gfx:0 "Corononense" #NT!
> De acuerdo! Entonces la primera letra tendría que ir en minúscula: "de las Tierras de la Corona".

¡Si! Tendría que ir en minúsculas.

Haz los cambios para subirlo, cuando puedas.

2023-06-25 10:49 UTC, closed without merging